# Generated by Django 4.2.7 on 2023-11-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='receipe_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipe'),
        ),
    ]
